# Testing things
Testing if processed data works with utils functions

In [8]:
import pandas as pd
import numpy as np
import json
from importlib import reload
from src import utils

# Reload utils module to get the latest changes
reload(utils)

<module 'src.utils' from '/Users/cadenp/Documents/GitHub/DSC180B_FinalProject/src/utils.py'>

In [9]:
# Load the JSON data
with open("data/processed/0021500622_processed.json", "r") as f:
    game = json.load(f)

# Assign possession for events w/o possession info according to closest player to ball
for event in game:
    utils.assign_event_possession(event)

In [10]:
dataset = utils.build_offensive_dataset(game, max_frames=150)
print(dataset)

<xarray.Dataset> Size: 3MB
Dimensions:    (play: 281, time: 150, player: 5, coord: 2)
Coordinates:
  * play       (play) int64 2kB 0 1 2 3 4 5 6 7 ... 274 275 276 277 278 279 280
  * time       (time) int64 1kB 0 1 2 3 4 5 6 7 ... 143 144 145 146 147 148 149
  * player     (player) int64 40B 0 1 2 3 4
  * coord      (coord) <U1 8B 'x' 'y'
Data variables:
    positions  (play, time, player, coord) float64 3MB 6.443 22.26 ... 40.19


In [ ]:
## EXAMPLE USAGE OF DistanceProfile
# Compare two events (first frames)
X = dataset.positions[0, 0, :, :].values  # first event, first frame
Y = dataset.positions[1, 0, :, :].values  # second event, first frame

# DistanceProfile
dp = utils.DistanceProfile(X, Y)
dist_matrix = dp.compute_W_matrix(X, Y)
print ("Distance matrix:\n", dist_matrix)

It.  |Loss        |Relative loss|Absolute loss
------------------------------------------------
    0|4.911300e+03|0.000000e+00|0.000000e+00
    1|2.728484e-12|1.800011e+15|4.911300e+03
    2|2.728484e-12|0.000000e+00|0.000000e+00
Distance matrix:
 [[0.2 0.  0.  0.  0. ]
 [0.  0.2 0.  0.  0. ]
 [0.  0.  0.2 0.  0. ]
 [0.  0.  0.  0.2 0. ]
 [0.  0.  0.  0.  0.2]]


In [ ]:
# calculate L-Norm distance matrices
dist_X, dist_Y = dp.compute_LN_matrix(X, Y, ord=2)  # Euclidean norm
print("Offense pairwise distances:\n", dist_X)
print("Defense pairwise distances:\n", dist_Y)

Offense pairwise distances:
 [[ 0.         21.12624859  5.86996826 31.60409151 14.18691794]
 [21.12624859  0.         15.7821068  42.5523995  18.8702791 ]
 [ 5.86996826 15.7821068   0.         35.43271672 14.55959885]
 [31.60409151 42.5523995  35.43271672  0.         23.78746014]
 [14.18691794 18.8702791  14.55959885 23.78746014  0.        ]]
Defense pairwise distances:
 [[ 0.         21.12624859  5.86996826 31.60409151 14.18691794]
 [21.12624859  0.         15.7821068  42.5523995  18.8702791 ]
 [ 5.86996826 15.7821068   0.         35.43271672 14.55959885]
 [31.60409151 42.5523995  35.43271672  0.         23.78746014]
 [14.18691794 18.8702791  14.55959885 23.78746014  0.        ]]
